#
# BTstack example 'hid_mouse_demo' for ESP32 port
#
# Generated by /home/noel/Documents/esp32_projects/btstack/port/esp32
# On Fri Jan 13 12:12:29 2023

PROJECT_NAME := hid_mouse_demo

include $(IDF_PATH)/make/project.mk
